module.exports.confFiles = [
  'primers/2008-12-03_linux-basics/config.json',
  'primers/2012-02-12_box-2-d-basics-part-1/conf.json',
  'primers/2012-03-14_regex-basics/conf.json',
  'primers/2013-07-23_markdown-basics/conf.json',
  'primers/2015-09-17_couchdb-primer-part-1-the-basics/conf.json',
  'primers/2015-10-02_couchdb-primer-part-2-design-documents-and-views/conf.json',
  'tips/2011-05-22_building-mobile-games-in-adobe-air-techniques-used-in-jumping-droid/conf.json',
  'tips/2011-11-15_getting-certificates-and-provisioning-profiles-for-ios-on-windows/conf.json',
  'tips/2011-12-01_building-ios-app-with-adobe-air-things-learnt-when-developing-colorbyshape-app/conf.json',
  'tips/2012-01-19_saving-and-loading-complex-objects-from-a-file-with-flashplayer/conf.json',
  'tips/2016-03-15_creating-command-line-tools-with-nodejs/conf.json',
  'tips/2017-03-06_testing-articles-with-images/conf.json',
  'tutorials/2011-05-10_starting-with-air-for-android-and-ios-building-one-app-for-both-platforms/conf.json',
  'tutorials/2011-08-06_simple-pathfinding-algorithm-in-actionscript-3/conf.json',
  'tutorials/2012-09-05_agal-multitexture-shader/conf.json',
  'tutorials/2013-06-02_using-modules-and-dependency-management-in-javascript-applications-with-amd-require-js/conf.json'
];

module.exports.allFiles = [
  'conf-global.json',
  'primers/2008-12-03_linux-basics/brief.html',
  'primers/2008-12-03_linux-basics/config.json',
  'primers/2008-12-03_linux-basics/extended.md',
  'primers/2012-02-12_box-2-d-basics-part-1/brief.html',
  'primers/2012-02-12_box-2-d-basics-part-1/conf.json',
  'primers/2012-02-12_box-2-d-basics-part-1/extended.html',
  'primers/2012-03-14_regex-basics/brief.html',
  'primers/2012-03-14_regex-basics/conf.json',
  'primers/2012-03-14_regex-basics/extended.md',
  'primers/2013-07-23_markdown-basics/brief.html',
  'primers/2013-07-23_markdown-basics/conf.json',
  'primers/2013-07-23_markdown-basics/extended.md',
  'primers/2015-09-17_couchdb-primer-part-1-the-basics/brief.html',
  'primers/2015-09-17_couchdb-primer-part-1-the-basics/conf.json',
  'primers/2015-09-17_couchdb-primer-part-1-the-basics/extended.md',
  'primers/2015-10-02_couchdb-primer-part-2-design-documents-and-views/brief.html',
  'primers/2015-10-02_couchdb-primer-part-2-design-documents-and-views/conf.json',
  'primers/2015-10-02_couchdb-primer-part-2-design-documents-and-views/extended.md',
  'tips/2011-05-22_building-mobile-games-in-adobe-air-techniques-used-in-jumping-droid/brief.html',
  'tips/2011-05-22_building-mobile-games-in-adobe-air-techniques-used-in-jumping-droid/conf.json',
  'tips/2011-05-22_building-mobile-games-in-adobe-air-techniques-used-in-jumping-droid/extended.html',
  'tips/2011-11-15_getting-certificates-and-provisioning-profiles-for-ios-on-windows/brief.html',
  'tips/2011-11-15_getting-certificates-and-provisioning-profiles-for-ios-on-windows/conf.json',
  'tips/2011-11-15_getting-certificates-and-provisioning-profiles-for-ios-on-windows/extended.html',
  'tips/2011-12-01_building-ios-app-with-adobe-air-things-learnt-when-developing-colorbyshape-app/brief.html',
  'tips/2011-12-01_building-ios-app-with-adobe-air-things-learnt-when-developing-colorbyshape-app/conf.json',
  'tips/2011-12-01_building-ios-app-with-adobe-air-things-learnt-when-developing-colorbyshape-app/extended.html',
  'tips/2012-01-19_saving-and-loading-complex-objects-from-a-file-with-flashplayer/brief.html',
  'tips/2012-01-19_saving-and-loading-complex-objects-from-a-file-with-flashplayer/conf.json',
  'tips/2012-01-19_saving-and-loading-complex-objects-from-a-file-with-flashplayer/extended.html',
  'tips/2016-03-15_creating-command-line-tools-with-nodejs/brief.html',
  'tips/2016-03-15_creating-command-line-tools-with-nodejs/conf.json',
  'tips/2016-03-15_creating-command-line-tools-with-nodejs/extended.md',
  'tips/2017-03-06_testing-articles-with-images/assets/large_img1.jpg',
  'tips/2017-03-06_testing-articles-with-images/assets/large_img2.jpg',
  'tips/2017-03-06_testing-articles-with-images/assets/readme.txt',
  'tips/2017-03-06_testing-articles-with-images/brief.html',
  'tips/2017-03-06_testing-articles-with-images/conf.json',
  'tips/2017-03-06_testing-articles-with-images/extended.md',
  'tips/2017-03-06_testing-articles-with-images/index.html',
  'tips/2017-03-06_testing-articles-with-images/test_img1.jpeg',
  'tips/2017-03-06_testing-articles-with-images/test_img2.jpeg',
  'tips/2017-03-06_testing-articles-with-images/test_img3.jpeg',
  'tutorials/2011-05-10_starting-with-air-for-android-and-ios-building-one-app-for-both-platforms/brief.html',
  'tutorials/2011-05-10_starting-with-air-for-android-and-ios-building-one-app-for-both-platforms/conf.json',
  'tutorials/2011-05-10_starting-with-air-for-android-and-ios-building-one-app-for-both-platforms/extended.html',
  'tutorials/2011-08-06_simple-pathfinding-algorithm-in-actionscript-3/brief.html',
  'tutorials/2011-08-06_simple-pathfinding-algorithm-in-actionscript-3/conf.json',
  'tutorials/2011-08-06_simple-pathfinding-algorithm-in-actionscript-3/extended.html',
  'tutorials/2012-09-05_agal-multitexture-shader/brief.html',
  'tutorials/2012-09-05_agal-multitexture-shader/conf.json',
  'tutorials/2012-09-05_agal-multitexture-shader/extended.html',
  'tutorials/2013-06-02_using-modules-and-dependency-management-in-javascript-applications-with-amd-require-js/brief.html',
  'tutorials/2013-06-02_using-modules-and-dependency-management-in-javascript-applications-with-amd-require-js/conf.json',
  'tutorials/2013-06-02_using-modules-and-dependency-management-in-javascript-applications-with-amd-require-js/extended.html',
  'tutorials/only-one-with-yaml/conf.yaml1'
];

module.exports.sampleConfigFile = {
  filePath: 'primers/2008-12-03_linux-basics/config.json',
  fileContent: JSON.stringify({
    "author": {
      "name": "sigman"
    },
    "category": "primers",
    "content": {
      "brief": "brief.html",
      "extended": "extended.md",
      "extendedType": "md"
    },
    "publishedDate": "2008-12-03T00:00:00.000+0000",
    "state": "published",
    "tags": ["linux"],
    "title": "Linux basics"
  })
};

module.exports.old = [ { dirPath: 'primers/2008-12-03_linux-basics',
    confFile: 'config.json',
    staticFiles: [ 'brief.html', 'extended.md' ] },
  { dirPath: 'primers/2012-02-12_box-2-d-basics-part-1',
    confFile: 'conf.json',
    staticFiles: [ 'brief.html', 'extended.html' ] },
  { dirPath: 'primers/2012-03-14_regex-basics',
    confFile: 'conf.json',
    staticFiles: [ 'brief.html', 'extended.md' ] },
  { dirPath: 'primers/2013-07-23_markdown-basics',
    confFile: 'conf.json',
    staticFiles: [ 'brief.html', 'extended.md' ] },
  { dirPath: 'primers/2015-09-17_couchdb-primer-part-1-the-basics',
    confFile: 'conf.json',
    staticFiles: [ 'brief.html', 'extended.md' ] },
  { dirPath: 'primers/2015-10-02_couchdb-primer-part-2-design-documents-and-views',
    confFile: 'conf.json',
    staticFiles: [ 'brief.html', 'extended.md' ] },
  { dirPath: 'tips/2011-05-22_building-mobile-games-in-adobe-air-techniques-used-in-jumping-droid',
    confFile: 'conf.json',
    staticFiles: [ 'brief.html', 'extended.html' ] },
  { dirPath: 'tips/2011-11-15_getting-certificates-and-provisioning-profiles-for-ios-on-windows',
    confFile: 'conf.json',
    staticFiles: [ 'brief.html', 'extended.html' ] },
  { dirPath: 'tips/2011-12-01_building-ios-app-with-adobe-air-things-learnt-when-developing-colorbyshape-app',
    confFile: 'conf.json',
    staticFiles: [ 'brief.html', 'extended.html' ] },
  { dirPath: 'tips/2012-01-19_saving-and-loading-complex-objects-from-a-file-with-flashplayer',
    confFile: 'conf.json',
    staticFiles: [ 'brief.html', 'extended.html' ] },
  { dirPath: 'tips/2016-03-15_creating-command-line-tools-with-nodejs',
    confFile: 'conf.json',
    staticFiles: [ 'brief.html', 'extended.md' ] },
  { dirPath: 'tips/2017-03-06_testing-articles-with-images',
    confFile: 'conf.json',
    staticFiles:
     [ 'assets/large_img1.jpg',
       'assets/large_img2.jpg',
       'assets/readme.txt',
       'brief.html',
       'extended.md',
       'index.html',
       'test_img1.jpeg',
       'test_img2.jpeg',
       'test_img3.jpeg' ] },
  { dirPath: 'tutorials/2011-05-10_starting-with-air-for-android-and-ios-building-one-app-for-both-platforms',
    confFile: 'conf.json',
    staticFiles: [ 'brief.html', 'extended.html' ] },
  { dirPath: 'tutorials/2011-08-06_simple-pathfinding-algorithm-in-actionscript-3',
    confFile: 'conf.json',
    staticFiles: [ 'brief.html', 'extended.html' ] },
  { dirPath: 'tutorials/2012-09-05_agal-multitexture-shader',
    confFile: 'conf.json',
    staticFiles: [ 'brief.html', 'extended.html' ] },
  { dirPath: 'tutorials/2013-06-02_using-modules-and-dependency-management-in-javascript-applications-with-amd-require-js',
    confFile: 'conf.json',
    staticFiles: [ 'brief.html', 'extended.html' ] }
];
