module.exports = [ { dirPath: 'primers/2008-12-03_linux-basics',
    confFile: 'config.json',
    staticFiles: [ 'brief.html', 'extended.md' ] },
  { dirPath: 'primers/2012-02-12_box-2-d-basics-part-1',
    confFile: 'conf.json',
    staticFiles: [ 'brief.html', 'extended.html' ] },
  { dirPath: 'primers/2012-03-14_regex-basics',
    confFile: 'conf.json',
    staticFiles: [ 'brief.html', 'extended.md' ] },
  { dirPath: 'primers/2013-07-23_markdown-basics',
    confFile: 'conf.json',
    staticFiles: [ 'brief.html', 'extended.md' ] },
  { dirPath: 'primers/2015-09-17_couchdb-primer-part-1-the-basics',
    confFile: 'conf.json',
    staticFiles: [ 'brief.html', 'extended.md' ] },
  { dirPath: 'primers/2015-10-02_couchdb-primer-part-2-design-documents-and-views',
    confFile: 'conf.json',
    staticFiles: [ 'brief.html', 'extended.md' ] },
  { dirPath: 'tips/2011-05-22_building-mobile-games-in-adobe-air-techniques-used-in-jumping-droid',
    confFile: 'conf.json',
    staticFiles: [ 'brief.html', 'extended.html' ] },
  { dirPath: 'tips/2011-11-15_getting-certificates-and-provisioning-profiles-for-ios-on-windows',
    confFile: 'conf.json',
    staticFiles: [ 'brief.html', 'extended.html' ] },
  { dirPath: 'tips/2011-12-01_building-ios-app-with-adobe-air-things-learnt-when-developing-colorbyshape-app',
    confFile: 'conf.json',
    staticFiles: [ 'brief.html', 'extended.html' ] },
  { dirPath: 'tips/2012-01-19_saving-and-loading-complex-objects-from-a-file-with-flashplayer',
    confFile: 'conf.json',
    staticFiles: [ 'brief.html', 'extended.html' ] },
  { dirPath: 'tips/2016-03-15_creating-command-line-tools-with-nodejs',
    confFile: 'conf.json',
    staticFiles: [ 'brief.html', 'extended.md' ] },
  { dirPath: 'tips/2017-03-06_testing-articles-with-images',
    confFile: 'conf.json',
    staticFiles:
     [ 'assets/large_img1.jpg',
       'assets/large_img2.jpg',
       'assets/readme.txt',
       'brief.html',
       'extended.md',
       'index.html',
       'test_img1.jpeg',
       'test_img2.jpeg',
       'test_img3.jpeg' ] },
  { dirPath: 'tutorials/2011-05-10_starting-with-air-for-android-and-ios-building-one-app-for-both-platforms',
    confFile: 'conf.json',
    staticFiles: [ 'brief.html', 'extended.html' ] },
  { dirPath: 'tutorials/2011-08-06_simple-pathfinding-algorithm-in-actionscript-3',
    confFile: 'conf.json',
    staticFiles: [ 'brief.html', 'extended.html' ] },
  { dirPath: 'tutorials/2012-09-05_agal-multitexture-shader',
    confFile: 'conf.json',
    staticFiles: [ 'brief.html', 'extended.html' ] },
  { dirPath: 'tutorials/2013-06-02_using-modules-and-dependency-management-in-javascript-applications-with-amd-require-js',
    confFile: 'conf.json',
    staticFiles: [ 'brief.html', 'extended.html' ] }
];
